"""Initial schema

Revision ID: fc65c4e81928
Revises: 
Create Date: 2026-05-22 02:24:53.623525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc65c4e81928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('question_banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('user_status', sa.String(length=30), server_default='PENDING_VERIFICATION', nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_user_status', ['user_status'], unique=False)

    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_email_verification_tokens_token_hash', ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_email_verification_tokens_user_id_is_used', ['user_id', 'is_used'], unique=False)

    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reset_code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_password_reset_codes_user_id_is_used', ['user_id', 'is_used'], unique=False)

    op.create_table('plan_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_id', name='unique_plan_feature')
    )
    with op.batch_alter_table('plan_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_features_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_features_plan_id'), ['plan_id'], unique=False)

    op.create_table('question_choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_choices_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index('ix_question_choices_status', ['status'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_id', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_sessions_user_id_is_active', ['user_id', 'is_active'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('subject_assignment_mode', sa.String(length=30), nullable=True),
    sa.Column('is_verified_by_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index('ix_workspaces_kind', ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index('ix_workspaces_status', ['status'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='unique_user_workspace')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_memberships_workspace_role', ['workspace_id', 'role'], unique=False)
        batch_op.create_index('ix_memberships_workspace_status', ['workspace_id', 'status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_subscriptions_workspace_status', ['workspace_id', 'status'], unique=False)

    op.create_table('workspace_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('workspace_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_subscriptions_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_workspace_subscriptions_workspace_status', ['workspace_id', 'status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_subscription_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_subscription_id'], ['workspace_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_workspace_subscription_id'), ['workspace_subscription_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_membership_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_created_by_membership_id'), ['created_by_membership_id'], unique=False)
        batch_op.create_index('ix_subjects_workspace_code', ['workspace_id', 'code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_subjects_workspace_name', ['workspace_id', 'name'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('grading_mode', sa.String(length=50), nullable=True),
    sa.Column('created_by_membership_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('availability_time_mode', sa.String(length=30), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('entry_window_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index('ix_tests_availability_time_mode', ['availability_time_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_created_by_membership_id'), ['created_by_membership_id'], unique=False)
        batch_op.create_index('ix_tests_status', ['status'], unique=False)

    op.create_table('workspace_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('assigned_role', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('invited_by_membership_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('workspace_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invites_invited_by_membership_id'), ['invited_by_membership_id'], unique=False)
        batch_op.create_index('ix_workspace_invites_status', ['status'], unique=False)
        batch_op.create_index('ix_workspace_invites_workspace_email', ['workspace_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invites_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memberships_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'subject_id', name='unique_membership_subject')
    )
    with op.batch_alter_table('memberships_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_subjects_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_subjects_subject_id'), ['subject_id'], unique=False)

    op.create_table('test_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_membership_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='IN_PROGRESS', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_attempts_student_membership_id'), ['student_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_attempts_test_id'), ['test_id'], unique=False)
        batch_op.create_index('ix_test_attempts_test_status', ['test_id', 'status'], unique=False)
        batch_op.create_index('ix_test_attempts_test_student', ['test_id', 'student_membership_id'], unique=False)
        batch_op.create_index('ix_test_attempts_user_id', ['user_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_topics_subject_name', ['subject_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_topics_workspace_subject', ['workspace_id', 'subject_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('question_choices_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_choices_id'], ['question_choices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_choices_id'), ['question_choices_id'], unique=False)
        batch_op.create_index('ix_questions_question_type_id', ['question_type_id'], unique=False)
        batch_op.create_index('ix_questions_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('selected_choice_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('earned_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['question_choices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='unique_attempt_question')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_answers_selected_choice_id'), ['selected_choice_id'], unique=False)

    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'question_id', name='unique_test_question')
    )
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_questions_test_id'), ['test_id'], unique=False)
        batch_op.create_index('ix_test_questions_test_status', ['test_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_test_questions_test_status')
        batch_op.drop_index(batch_op.f('ix_test_questions_test_id'))
        batch_op.drop_index(batch_op.f('ix_test_questions_question_id'))

    op.drop_table('test_questions')
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answers_selected_choice_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_answers_attempt_id'))

    op.drop_table('attempt_answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index('ix_questions_status')
        batch_op.drop_index('ix_questions_question_type_id')
        batch_op.drop_index(batch_op.f('ix_questions_question_choices_id'))
        batch_op.drop_index(batch_op.f('ix_questions_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_questions_bank_id'))

    op.drop_table('questions')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('ix_topics_workspace_subject')
        batch_op.drop_index(batch_op.f('ix_topics_workspace_id'))
        batch_op.drop_index('ix_topics_subject_name')
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))

    op.drop_table('topics')
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_test_attempts_user_id')
        batch_op.drop_index('ix_test_attempts_test_student')
        batch_op.drop_index('ix_test_attempts_test_status')
        batch_op.drop_index(batch_op.f('ix_test_attempts_test_id'))
        batch_op.drop_index(batch_op.f('ix_test_attempts_student_membership_id'))

    op.drop_table('test_attempts')
    with op.batch_alter_table('memberships_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_subjects_subject_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_subjects_membership_id'))

    op.drop_table('memberships_subjects')
    with op.batch_alter_table('workspace_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invites_workspace_id'))
        batch_op.drop_index('ix_workspace_invites_workspace_email')
        batch_op.drop_index('ix_workspace_invites_status')
        batch_op.drop_index(batch_op.f('ix_workspace_invites_invited_by_membership_id'))

    op.drop_table('workspace_invites')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index('ix_tests_status')
        batch_op.drop_index(batch_op.f('ix_tests_created_by_membership_id'))
        batch_op.drop_index('ix_tests_availability_time_mode')

    op.drop_table('tests')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index('ix_subjects_workspace_name')
        batch_op.drop_index(batch_op.f('ix_subjects_workspace_id'))
        batch_op.drop_index('ix_subjects_workspace_code')
        batch_op.drop_index(batch_op.f('ix_subjects_created_by_membership_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_workspace_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_payments_transaction_id'))
        batch_op.drop_index('ix_payments_status')

    op.drop_table('payments')
    with op.batch_alter_table('workspace_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_workspace_subscriptions_workspace_status')
        batch_op.drop_index(batch_op.f('ix_workspace_subscriptions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_subscriptions_plan_id'))

    op.drop_table('workspace_subscriptions')
    op.drop_table('workspace_profiles')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_workspace_status')
        batch_op.drop_index(batch_op.f('ix_subscriptions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_memberships_workspace_status')
        batch_op.drop_index('ix_memberships_workspace_role')
        batch_op.drop_index(batch_op.f('ix_memberships_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index('ix_workspaces_status')
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_user_id'))
        batch_op.drop_index('ix_workspaces_kind')

    op.drop_table('workspaces')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_id_is_active')
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('question_choices', schema=None) as batch_op:
        batch_op.drop_index('ix_question_choices_status')
        batch_op.drop_index(batch_op.f('ix_question_choices_owner_user_id'))

    op.drop_table('question_choices')
    with op.batch_alter_table('plan_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_features_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_features_feature_id'))

    op.drop_table('plan_features')
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_password_reset_codes_user_id_is_used')
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_user_id'))

    op.drop_table('password_reset_codes')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_email_verification_tokens_user_id_is_used')
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_user_id'))
        batch_op.drop_index('ix_email_verification_tokens_token_hash')

    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_user_status')

    op.drop_table('users')
    op.drop_table('question_types')
    op.drop_table('question_banks')
    op.drop_table('plans')
    op.drop_table('features')
    # ### end Alembic commands ###
